package com.paulzhangcc.demo.dao.oracle.mapper;

import com.paulzhangcc.demo.dao.oracle.DO.DemoDO;
import org.apache.ibatis.jdbc.SQL;

public class DemoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO
     *
     * @mbg.generated
     */
    public String insertSelective(DemoDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("DEMO");
        
        if (record.getId() != null) {
            sql.VALUES("ID", "#{id,jdbcType=NUMERIC}");
        }
        
        if (record.getUserName() != null) {
            sql.VALUES("USER_NAME", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getAmount() != null) {
            sql.VALUES("AMOUNT", "#{amount,jdbcType=NUMERIC}");
        }
        
        if (record.getAge() != null) {
            sql.VALUES("AGE", "#{age,jdbcType=NUMERIC}");
        }
        
        if (record.getCash() != null) {
            sql.VALUES("CASH", "#{cash,jdbcType=NUMERIC}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(DemoDO record) {
        SQL sql = new SQL();
        sql.UPDATE("DEMO");
        
        if (record.getUserName() != null) {
            sql.SET("USER_NAME = #{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getAmount() != null) {
            sql.SET("AMOUNT = #{amount,jdbcType=NUMERIC}");
        }
        
        if (record.getAge() != null) {
            sql.SET("AGE = #{age,jdbcType=NUMERIC}");
        }
        
        if (record.getCash() != null) {
            sql.SET("CASH = #{cash,jdbcType=NUMERIC}");
        }
        
        sql.WHERE("ID = #{id,jdbcType=NUMERIC}");
        
        return sql.toString();
    }
}